# Generated by Django 4.2.10 on 2024-11-22 08:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavesrequests',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employeeleavesrequests',
            name='leave_day_type',
        ),
        migrations.RemoveField(
            model_name='employeeleavesrequests',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='employeeleavesrequests',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves_requests', to='employee.employee'),
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeavesRequestsDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('leave_day_type', models.CharField(choices=[('Full day', 'Full day'), ('Half day (1st half)', 'Half day (1st half)'), ('Half day (2nd half)', 'Half day (2nd half)')], default='Full day', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves_requests_dates', to='employee.employeeleavesrequests')),
            ],
        ),
    ]
