# Generated by Django 5.1.2 on 2024-11-25 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeleavesbalance_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavesbalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leavetypeindex'),
        ),
        migrations.AlterField(
            model_name='employeeleavesbalance',
            name='remaining_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employeeleavesbalance',
            name='used_leaves',
            field=models.FloatField(default=0),
        ),
    ]
