# Generated by Django 4.2.10 on 2024-11-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_leavepolicytypes_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicytypes',
            name='carry_forward_days',
            field=models.FloatField(default=0),
        ),
    ]
