# Generated by Django 5.1.3 on 2025-01-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_created_by_employeeattachments_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattachments',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
    ]
