# Generated by Django 5.1.2 on 2024-11-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeleavesbalance_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeleavesbalance',
            name='used_leaves',
        ),
    ]
