# Generated by Django 5.1.2 on 2024-11-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employeeleavesbalance_used_leaves'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeLeavesBalance',
        ),
    ]
