# Generated by Django 5.1.2 on 2024-11-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employeeleavesrequests_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavesrequestsdates',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves_requests_dates', to='employee.employeeleavesrequests'),
        ),
        migrations.DeleteModel(
            name='EmployeeLeavesBalance',
        ),
    ]
